version: '2'

services:
  cian-process:
    restart: always
    image: cian-process
    build: .
    environment:
      - PYTONUNBUFFERED=1
      - PYTHONPATH=/app/
    volumes:
      - ".:/app"
    entrypoint:
      - python
      - /app/process.py

  mongo:
    restart: always
    image: mongo
#    ports:
#      - 27017:27017
#    command: --bind_ip 0.0.0.0
    volumes:
      - "../mongo_data:/data/db"


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 2Z64IFgOtQznAAYJ5k2W4voY3Dd88T
