MONGO_HOST = 'mongo'
MONGO_PORT = 27017

MONGO_CIAN_COLLECTION = 'cian_offers'

CIAN_UPDATE_INTERVAL = 5 * 60  # 5 minutes
CIAN_UPDATE_INTERVAL_ERROR = 60  # 1 minute

RUCAPCHA_TOKEN = 'TOKEN_HERE'

TELEGRAM_BOT_TOKEN = 'TOKEN_HERE'
TELEGRAM_CHAT_ID = 'ID_HERE'
